#!/bin/bash
uname=$(uname)
[[ $uname == Darwin ]] && platform=bin-osx
[[ $uname == Linux  ]] && platform=bin-linux64

[[ -z "$uname" ]] && {
    echo Cannot determine platform.
    exit 1
}

cd "$(dirname $0)" || {
    echo Cannot change directory to script directory.
    exit 1
}

cd $platform || {
    echo "Platform folder ($platform) does not exist or is not readable."
    exit 1
}

./calcterm "$@"
